name: Heroku Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.1.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: calm-eyrie-94012
          heroku_email: expect.nothin9@gmail.com
          healthcheck: https://calm-eyrie-94012.herokuapp.com/